// FNG – Echos of Names: Vollständige Namensliste
export const names = [
  {
    welt: "Antanar",
    rasse: "Narbaak",
    geschlecht: "männlich",
    namen: [
      { name: "Grolmar", herkunft: "Tarmuk" },
      { name: "Tharak", herkunft: "Lundak" },
      { name: "Borjun", herkunft: "Narbek" },
      { name: "Vaknor", herkunft: "Noro" },
      { name: "Drummak", herkunft: "Tarmuk" },
      { name: "Karrun", herkunft: "Lundak" },
      { name: "Zurbok", herkunft: "Tarmuk" },
      { name: "Mak'tol", herkunft: "Narbek" },
      { name: "Ruggan", herkunft: "Tarmuk" },
      { name: "Tholrek", herkunft: "Narbek" },
      { name: "Darnak", herkunft: "Noro" },
      { name: "Zulkar", herkunft: "Narbek" },
      { name: "Nargul", herkunft: "Tarmuk" },
      { name: "Rukmar", herkunft: "Lundak" },
      { name: "Jarnok", herkunft: "Narbek" },
      { name: "Vultag", herkunft: "Noro" },
      { name: "Grashak", herkunft: "Tarmuk" },
      { name: "Brogar", herkunft: "Lundak" },
      { name: "Harnok", herkunft: "Lundak" },
      { name: "Trukkal", herkunft: "Tarmuk" },
      { name: "Folgak", herkunft: "Tarmuk" },
      { name: "Grunnar", herkunft: "Narbek" },
      { name: "Tarnog", herkunft: "Noro" },
      { name: "Jurkhan", herkunft: "Lundak" },
      { name: "Mokgar", herkunft: "Tarmuk" },
      { name: "Zarnor", herkunft: "Narbek" },
      { name: "Drekal", herkunft: "Tarmuk" },
      { name: "Narvak", herkunft: "Noro" },
      { name: "Throndak", herkunft: "Narbek" },
      { name: "Vagruk", herkunft: "Tarmuk" },
      { name: "Lorhak", herkunft: "Lundak" },
      { name: "Kundor", herkunft: "Narbek" },
      { name: "Hagrim", herkunft: "Tarmuk" },
      { name: "Ragnor", herkunft: "Lundak" },
      { name: "Ulgath", herkunft: "Noro" },
      { name: "Torjak", herkunft: "Tarmuk" },
      { name: "Durmal", herkunft: "Narbek" },
      { name: "Gharnek", herkunft: "Tarmuk" },
      { name: "Brolgar", herkunft: "Lundak" },
      { name: "Zarvok", herkunft: "Noro" }
    ]
  },
  {
    welt: "Antanar",
    rasse: "Narbaak",
    geschlecht: "weiblich",
    namen: [
      { name: "Tarra", herkunft: "Lundak" },
      { name: "Kahni", herkunft: "Narbek" },
      { name: "Vorga", herkunft: "Tarmuk" },
      { name: "Zulmai", herkunft: "Narbek" },
      { name: "Meksha", herkunft: "Tarmuk" },
      { name: "Runaak", herkunft: "Tarmuk" },
      { name: "Lirja", herkunft: "Noro" },
      { name: "Sha'makha", herkunft: "Narbek" },
      { name: "Norka", herkunft: "Lundak" },
      { name: "Yekta", herkunft: "Noro" },
      { name: "Gulvia", herkunft: "Narbek" },
      { name: "Thesha", herkunft: "Tarmuk" },
      { name: "Urani", herkunft: "Noro" },
      { name: "Mokta", herkunft: "Tarmuk" },
      { name: "Drahni", herkunft: "Lundak" },
      { name: "Karhja", herkunft: "Narbek" },
      { name: "Volsha", herkunft: "Tarmuk" },
      { name: "Narnu", herkunft: "Noro" },
      { name: "Kallira", herkunft: "Narbek" },
      { name: "Torkha", herkunft: "Tarmuk" },
      { name: "Zhavri", herkunft: "Narbek" },
      { name: "Eshana", herkunft: "Noro" },
      { name: "Durkha", herkunft: "Tarmuk" },
      { name: "Tahlja", herkunft: "Lundak" },
      { name: "Sarnika", herkunft: "Narbek" },
      { name: "Laghira", herkunft: "Noro" },
      { name: "Urkha", herkunft: "Tarmuk" },
      { name: "Brenka", herkunft: "Lundak" },
      { name: "Vulsha", herkunft: "Tarmuk" },
      { name: "Norvani", herkunft: "Noro" },
      { name: "Garkha", herkunft: "Tarmuk" },
      { name: "Jelva", herkunft: "Narbek" },
      { name: "Tranaak", herkunft: "Tarmuk" },
      { name: "Zirra", herkunft: "Lundak" },
      { name: "Omilka", herkunft: "Noro" },
      { name: "Teshma", herkunft: "Narbek" },
      { name: "Kharnika", herkunft: "Tarmuk" },
      { name: "Rokina", herkunft: "Noro" },
      { name: "Ma'kaal", herkunft: "Tarmuk" },
      { name: "Loranja", herkunft: "Lundak" }
    ]
  }
];{
  welt: "Antanar",
  rasse: "Ascandi",
  geschlecht: "männlich",
  namen: [
    { name: "Xar’Jin", herkunft: "Xaros" },
    { name: "Jir’Xun", herkunft: "Piloras" },
    { name: "Kurash", herkunft: "Arana" },
    { name: "Zer’Zijr", herkunft: "Xaros" },
    { name: "Varn’Kez", herkunft: "Piloras" },
    { name: "Thir’Zul", herkunft: "Arana" },
    { name: "Draxan", herkunft: "Xaros" },
    { name: "Kol’Zir", herkunft: "Piloras" },
    { name: "Jarak’Tul", herkunft: "Arana" },
    { name: "Nexur", herkunft: "Xaros" },
    { name: "Or’Vajek", herkunft: "Piloras" },
    { name: "Kren’Jor", herkunft: "Arana" },
    { name: "Xulgar", herkunft: "Xaros" },
    { name: "Zhar’Vix", herkunft: "Piloras" },
    { name: "Tarvok", herkunft: "Arana" },
    { name: "Skiraj", herkunft: "Xaros" },
    { name: "Ruk’Zen", herkunft: "Piloras" },
    { name: "Jor’Kel", herkunft: "Arana" },
    { name: "Ven’Shak", herkunft: "Xaros" },
    { name: "Zolmir", herkunft: "Piloras" },
    { name: "Frak’Jin", herkunft: "Arana" },
    { name: "Kar’Riz", herkunft: "Xaros" },
    { name: "Nashor", herkunft: "Piloras" },
    { name: "Xeren’Thal", herkunft: "Arana" },
    { name: "Zulvek", herkunft: "Xaros" },
    { name: "Dar’Khul", herkunft: "Piloras" },
    { name: "Orjax", herkunft: "Arana" },
    { name: "Vel’Karn", herkunft: "Xaros" },
    { name: "Kirajek", herkunft: "Piloras" },
    { name: "Tharnox", herkunft: "Arana" },
    { name: "Zar’Nek", herkunft: "Xaros" },
    { name: "Jexar", herkunft: "Piloras" },
    { name: "Rho’Dar", herkunft: "Arana" },
    { name: "Vulkor", herkunft: "Xaros" },
    { name: "Sharnok", herkunft: "Piloras" },
    { name: "Drexir", herkunft: "Arana" },
    { name: "Kav’Tur", herkunft: "Xaros" },
    { name: "Mon’Zal", herkunft: "Piloras" },
    { name: "Trivan", herkunft: "Arana" },
    { name: "Jhakor", herkunft: "Xaros" }
  ]
},
{
  welt: "Antanar",
  rasse: "Ascandi",
  geschlecht: "weiblich",
  namen: [
    { name: "Veyra’Shal", herkunft: "Arana" },
    { name: "Zira’Khen", herkunft: "Piloras" },
    { name: "Lashara", herkunft: "Xaros" },
    { name: "Thaleksa", herkunft: "Arana" },
    { name: "Nexa’Jir", herkunft: "Piloras" },
    { name: "Sha’Vora", herkunft: "Xaros" },
    { name: "Kireza", herkunft: "Arana" },
    { name: "Xani’Vel", herkunft: "Piloras" },
    { name: "Zyreth", herkunft: "Xaros" },
    { name: "Rilasha", herkunft: "Arana" },
    { name: "Jorra’Nae", herkunft: "Piloras" },
    { name: "Vel’Rina", herkunft: "Xaros" },
    { name: "Tashara", herkunft: "Arana" },
    { name: "Mezari", herkunft: "Piloras" },
    { name: "Kavra’Zen", herkunft: "Xaros" },
    { name: "Yul’Kisa", herkunft: "Arana" },
    { name: "Thyressa", herkunft: "Piloras" },
    { name: "Or’Lyra", herkunft: "Xaros" },
    { name: "Daryen", herkunft: "Arana" },
    { name: "Sel'Kora", herkunft: "Piloras" },
    { name: "Zahlira", herkunft: "Xaros" },
    { name: "Nurex", herkunft: "Arana" },
    { name: "Kasira", herkunft: "Piloras" },
    { name: "Ves’Thal", herkunft: "Xaros" },
    { name: "Elarin", herkunft: "Arana" },
    { name: "Shurena", herkunft: "Piloras" },
    { name: "Fey'Zira", herkunft: "Xaros" },
    { name: "Lunasha", herkunft: "Arana" },
    { name: "Tivra'Keh", herkunft: "Piloras" },
    { name: "Xalira", herkunft: "Xaros" },
    { name: "Mirjha", herkunft: "Arana" },
    { name: "Vahr’Elin", herkunft: "Piloras" },
    { name: "Zanora", herkunft: "Xaros" },
    { name: "Kyra’Nesh", herkunft: "Arana" },
    { name: "Jelrisa", herkunft: "Piloras" },
    { name: "Solvara", herkunft: "Xaros" },
    { name: "Maelira", herkunft: "Arana" },
    { name: "Thy’Kessa", herkunft: "Piloras" },
    { name: "Xurella", herkunft: "Xaros" },
    { name: "Drah’Vina", herkunft: "Arana" }
  ]
}{
  welt: "Antanar",
  rasse: "Voruk",
  geschlecht: "männlich",
  namen: [
    { name: "Grakthar", herkunft: "Land" },
    { name: "Velmok", herkunft: "Land" },
    { name: "Tharnok", herkunft: "Land" },
    { name: "Krunjak", herkunft: "Land" },
    { name: "Bralgor", herkunft: "Land" },
    { name: "Zarnak", herkunft: "Land" },
    { name: "Drekhul", herkunft: "Land" },
    { name: "Morkal", herkunft: "Land" },
    { name: "Juktar", herkunft: "Land" },
    { name: "Grovak", herkunft: "Land" },
    { name: "Trezhak", herkunft: "Land" },
    { name: "Korrun", herkunft: "Land" },
    { name: "Throguk", herkunft: "Land" },
    { name: "Urmakh", herkunft: "Land" },
    { name: "Skarnok", herkunft: "Land" },
    { name: "Rulvar", herkunft: "Land" },
    { name: "Brakkon", herkunft: "Land" },
    { name: "Drexul", herkunft: "Land" },
    { name: "Varthuk", herkunft: "Land" },
    { name: "Krenjal", herkunft: "Land" },
    { name: "Zulgar", herkunft: "Land" },
    { name: "Frakor", herkunft: "Land" },
    { name: "Hulvak", herkunft: "Land" },
    { name: "Grunzor", herkunft: "Land" },
    { name: "Zhurak", herkunft: "Land" },
    
    { name: "Olumek", herkunft: "Wasser" },
    { name: "Kha’rel", herkunft: "Wasser" },
    { name: "Thaloran", herkunft: "Wasser" },
    { name: "Nurvak", herkunft: "Wasser" },
    { name: "Selgor", herkunft: "Wasser" },
    { name: "Vashrek", herkunft: "Wasser" },
    { name: "Lunrak", herkunft: "Wasser" },
    { name: "Jalvok", herkunft: "Wasser" },
    { name: "Morazul", herkunft: "Wasser" },
    { name: "Khoran", herkunft: "Wasser" },
    { name: "Zeralu", herkunft: "Wasser" },
    { name: "Velosh", herkunft: "Wasser" },
    { name: "Aurok", herkunft: "Wasser" },
    { name: "Nureth", herkunft: "Wasser" },
    { name: "Elvoran", herkunft: "Wasser" },
    { name: "Krulash", herkunft: "Wasser" },
    { name: "Ulmek", herkunft: "Wasser" },
    { name: "Marzol", herkunft: "Wasser" },
    { name: "Oljan", herkunft: "Wasser" },
    { name: "Revak", herkunft: "Wasser" },
    { name: "Halur", herkunft: "Wasser" },
    { name: "Zorkan", herkunft: "Wasser" },
    { name: "Ushanok", herkunft: "Wasser" },
    { name: "Velkash", herkunft: "Wasser" },
    { name: "Ithurak", herkunft: "Wasser" }
  ]
},
{
  welt: "Antanar",
  rasse: "Voruk",
  geschlecht: "weiblich",
  namen: [
    { name: "Varka", herkunft: "Land" },
    { name: "Threkha", herkunft: "Land" },
    { name: "Jalna", herkunft: "Land" },
    { name: "Drasha", herkunft: "Land" },
    { name: "Mokali", herkunft: "Land" },
    { name: "Trezna", herkunft: "Land" },
    { name: "Ulvira", herkunft: "Land" },
    { name: "Skelra", herkunft: "Land" },
    { name: "Gruvha", herkunft: "Land" },
    { name: "Kalrekha", herkunft: "Land" },
    { name: "Frona", herkunft: "Land" },
    { name: "Kharna", herkunft: "Land" },
    { name: "Brunaak", herkunft: "Land" },
    { name: "Zulrika", herkunft: "Land" },
    { name: "Drosha", herkunft: "Land" },
    { name: "Krava", herkunft: "Land" },
    { name: "Ulgra", herkunft: "Land" },
    { name: "Tralka", herkunft: "Land" },
    { name: "Voruna", herkunft: "Land" },
    { name: "Krenza", herkunft: "Land" },
    { name: "Zargha", herkunft: "Land" },
    { name: "Hulmira", herkunft: "Land" },
    { name: "Olkra", herkunft: "Land" },
    { name: "Shurni", herkunft: "Land" },
    { name: "Drekhala", herkunft: "Land" },

    { name: "Elvara", herkunft: "Wasser" },
    { name: "Selmira", herkunft: "Wasser" },
    { name: "Lunasha", herkunft: "Wasser" },
    { name: "Norvani", herkunft: "Wasser" },
    { name: "Taleka", herkunft: "Wasser" },
    { name: "Ushani", herkunft: "Wasser" },
    { name: "Khorali", herkunft: "Wasser" },
    { name: "Vireya", herkunft: "Wasser" },
    { name: "Zureli", herkunft: "Wasser" },
    { name: "Nalvira", herkunft: "Wasser" },
    { name: "Ithura", herkunft: "Wasser" },
    { name: "Malshi", herkunft: "Wasser" },
    { name: "Orlani", herkunft: "Wasser" },
    { name: "Khalma", herkunft: "Wasser" },
    { name: "Ulrika", herkunft: "Wasser" },
    { name: "Tharena", herkunft: "Wasser" },
    { name: "Jalura", herkunft: "Wasser" },
    { name: "Oshima", herkunft: "Wasser" },
    { name: "Vaskha", herkunft: "Wasser" },
    { name: "Lureth", herkunft: "Wasser" },
    { name: "Eshani", herkunft: "Wasser" },
    { name: "Moraya", herkunft: "Wasser" },
    { name: "Velara", herkunft: "Wasser" },
    { name: "Sharena", herkunft: "Wasser" },
    { name: "Zurika", herkunft: "Wasser" }
  ]
}{
  welt: "Antanar",
  rasse: "Heiler",
  geschlecht: "männlich",
  namen: [
    { name: "Hamut", herkunft: "Cesca" },
    { name: "Rakiel", herkunft: "Cesca" },
    { name: "Thanou", herkunft: "Cesca" },
    { name: "Koumash", herkunft: "Cesca" },
    { name: "Ashuron", herkunft: "Cesca" },
    { name: "Riolan", herkunft: "Cesca" },
    { name: "Keluar", herkunft: "Cesca" },
    { name: "Shanar", herkunft: "Cesca" },
    { name: "Marouel", herkunft: "Cesca" },
    { name: "Tharunel", herkunft: "Cesca" },
    { name: "Korashan", herkunft: "Cesca" },
    { name: "Umakel", herkunft: "Cesca" },
    { name: "Rhounek", herkunft: "Cesca" },
    { name: "Kaelun", herkunft: "Cesca" },
    { name: "Shaelinor", herkunft: "Cesca" },
    { name: "Ormelak", herkunft: "Cesca" },
    { name: "Theroun", herkunft: "Cesca" },
    { name: "Ashvakel", herkunft: "Cesca" },
    { name: "Darionel", herkunft: "Cesca" },
    { name: "Nourakem", herkunft: "Cesca" },
    { name: "Rashoum", herkunft: "Cesca" },
    { name: "Khaenal", herkunft: "Cesca" },
    { name: "Omareth", herkunft: "Cesca" },
    { name: "Valkior", herkunft: "Cesca" },
    { name: "Tournak", herkunft: "Cesca" },

    { name: "Kaelom", herkunft: "Rankom" },
    { name: "Shaemur", herkunft: "Rankom" },
    { name: "Ieronak", herkunft: "Rankom" },
    { name: "Usharel", herkunft: "Rankom" },
    { name: "Thorian", herkunft: "Rankom" },
    { name: "Kourath", herkunft: "Rankom" },
    { name: "Raomel", herkunft: "Rankom" },
    { name: "Ashioun", herkunft: "Rankom" },
    { name: "Nourik", herkunft: "Rankom" },
    { name: "Keliran", herkunft: "Rankom" },
    { name: "Riomesh", herkunft: "Rankom" },
    { name: "Valkemai", herkunft: "Rankom" },
    { name: "Eshalom", herkunft: "Rankom" },
    { name: "Thamalek", herkunft: "Rankom" },
    { name: "Korien", herkunft: "Rankom" },
    { name: "Uliranek", herkunft: "Rankom" },
    { name: "Dhamour", herkunft: "Rankom" },
    { name: "Sourikhael", herkunft: "Rankom" },
    { name: "Liaroun", herkunft: "Rankom" },
    { name: "Ashuakem", herkunft: "Rankom" },
    { name: "Rhalior", herkunft: "Rankom" },
    { name: "Toumash", herkunft: "Rankom" },
    { name: "Khaemorak", herkunft: "Rankom" },
    { name: "Elrakel", herkunft: "Rankom" },
    { name: "Zaurion", herkunft: "Rankom" }
  ]
},
{
  welt: "Antanar",
  rasse: "Heiler",
  geschlecht: "weiblich",
  namen: [
    { name: "Shaeliun", herkunft: "Cesca" },
    { name: "Rakinae", herkunft: "Cesca" },
    { name: "Thamara", herkunft: "Cesca" },
    { name: "Ashourel", herkunft: "Cesca" },
    { name: "Kelinae", herkunft: "Cesca" },
    { name: "Nourika", herkunft: "Cesca" },
    { name: "Khaela", herkunft: "Cesca" },
    { name: "Shavirae", herkunft: "Cesca" },
    { name: "Riomara", herkunft: "Cesca" },
    { name: "Eloura", herkunft: "Cesca" },
    { name: "Karasha", herkunft: "Cesca" },
    { name: "Ulinaya", herkunft: "Cesca" },
    { name: "Valkirae", herkunft: "Cesca" },
    { name: "Maelion", herkunft: "Cesca" },
    { name: "Tharenia", herkunft: "Cesca" },
    { name: "Isouna", herkunft: "Cesca" },
    { name: "Shaomiel", herkunft: "Cesca" },
    { name: "Lorikae", herkunft: "Cesca" },
    { name: "Tounia", herkunft: "Cesca" },
    { name: "Naelira", herkunft: "Cesca" },
    { name: "Kauriel", herkunft: "Cesca" },
    { name: "Eshomai", herkunft: "Cesca" },
    { name: "Thalouka", herkunft: "Cesca" },
    { name: "Ravaena", herkunft: "Cesca" },
    { name: "Oshmira", herkunft: "Cesca" },

    { name: "Khalari", herkunft: "Rankom" },
    { name: "Ashiunae", herkunft: "Rankom" },
    { name: "Raelima", herkunft: "Rankom" },
    { name: "Toumasha", herkunft: "Rankom" },
    { name: "Shaoriel", herkunft: "Rankom" },
    { name: "Velunae", herkunft: "Rankom" },
    { name: "Elkaia", herkunft: "Rankom" },
    { name: "Kourama", herkunft: "Rankom" },
    { name: "Nariael", herkunft: "Rankom" },
    { name: "Ushaena", herkunft: "Rankom" },
    { name: "Thalinae", herkunft: "Rankom" },
    { name: "Yorasha", herkunft: "Rankom" },
    { name: "Isurael", herkunft: "Rankom" },
    { name: "Meularia", herkunft: "Rankom" },
    { name: "Liorasha", herkunft: "Rankom" },
    { name: "Kaemiria", herkunft: "Rankom" },
    { name: "Zourali", herkunft: "Rankom" },
    { name: "Sharivae", herkunft: "Rankom" },
    { name: "Ashmora", herkunft: "Rankom" },
    { name: "Elinaou", herkunft: "Rankom" },
    { name: "Rhaliaen", herkunft: "Rankom" },
    { name: "Thourelis", herkunft: "Rankom" },
    { name: "Vourimae", herkunft: "Rankom" },
    { name: "Naevouka", herkunft: "Rankom" },
    { name: "Sariael", herkunft: "Rankom" }
  ]
}{
  welt: "Antanar",
  rasse: "Asvar",
  geschlecht: "männlich",
  namen: [
    "Eoralon",
    "Malior",
    "Thaevenor",
    "Iorakem",
    "Ultharel",
    "Aephoras",
    "Kaevinar",
    "Solirak",
    "Nauror",
    "Elthorian",
    "Vaeanor",
    "Thulorin",
    "Aomarik",
    "Ivenaroth",
    "Orelian",
    "Arkaeol",
    "Vaelmiron",
    "Yonareth",
    "Zhaeron",
    "Iorvelak",
    "Eshorak",
    "Torvianor",
    "Quelorin",
    "Naeroth",
    "Olviren",
    "Lyraemor",
    "Selvakon",
    "Iralor",
    "Aevaron",
    "Thalioren",
    "Yonakai",
    "Elvenak",
    "Vioraneth",
    "Khaeluron",
    "Mirvakel",
    "Thaelur",
    "Rhaelion",
    "Corvienor",
    "Arionak",
    "Ulviaren"
  ]
},
{
  welt: "Antanar",
  rasse: "Asvar",
  geschlecht: "weiblich",
  namen: [
    "Ae’lirien",
    "Ionael",
    "Ylvora",
    "Thaeviara",
    "Orianeth",
    "Seliora",
    "Elavien",
    "Kaenya",
    "Vaelira",
    "Lioraneth",
    "Urelia",
    "Thalena",
    "Aenyael",
    "Noralieth",
    "Evaraen",
    "Corvalira",
    "Naerithae",
    "Itharia",
    "Zhaelwyn",
    "Ismiraen",
    "Auraleth",
    "Eshyara",
    "Lywenara",
    "Thirael",
    "Valoreth",
    "Eluriena",
    "Myariel",
    "Saevaena",
    "Oriaveth",
    "Vaelyra",
    "Sharionae",
    "Elionea",
    "Iyvalae",
    "Noravaen",
    "Rhaelena",
    "Aenilira",
    "Yaraithae",
    "Vionera",
    "Aurireth",
    "Kaelionae"
  ]
}{
  welt: "Antanar",
  rasse: "Shin-Zun",
  geschlecht: "männlich",
  namen: [
    "Kai’Zhen",
    "Raku’Maru",
    "Shin’Kairos",
    "Joraku",
    "Zan’Toru",
    "Keshin",
    "Raido",
    "Vah’Zen",
    "Korinashi",
    "Thae’Maru",
    "Jinroku",
    "Ashiro",
    "Zukhen",
    "Ry’Kenji",
    "Soru’Tai",
    "Kenmae",
    "Daisho",
    "Lian’Kuro",
    "Torashin",
    "Kazekai",
    "Arikuro",
    "Sho’Ren",
    "Takami",
    "Kairan",
    "Jano’Tai",
    "Masho",
    "Kento’Ra",
    "Byakura",
    "Naro’Kai",
    "Zentaisho",
    "Haru’Zen",
    "Kiyoro",
    "Osaku",
    "Ronzai",
    "Kirashi",
    "Juro’Ken",
    "Daiki’Ren",
    "Tsuroka",
    "Fuyashi",
    "Raen’Kai"
  ]
},
{
  welt: "Antanar",
  rasse: "Shin-Zun",
  geschlecht: "weiblich",
  namen: [
    "Maeko",
    "Shin’Yara",
    "Kira’Len",
    "Satsuki",
    "Yure’Na",
    "Aino",
    "Hikari",
    "Zai’Mei",
    "Tomika",
    "Rei’Shira",
    "Kiyona",
    "Nami’Za",
    "Ayashi",
    "Sakurae",
    "Yuji’Na",
    "Tsuki’Mei",
    "Kaorina",
    "Rina’Su",
    "Maruka",
    "Elashi",
    "Fuyuna",
    "Kana’Lei",
    "Sayami",
    "Isuka",
    "No’Rika",
    "Taki’Noa",
    "Yamira",
    "Sho’Meika",
    "Aira’Kae",
    "Koharu",
    "Ren’Shika",
    "Miruki",
    "Yunae",
    "Naoko",
    "Haerika",
    "Misane",
    "Kureha",
    "Liah’Zen",
    "Tsumae",
    "Asunaka"
  ]
}{
  welt: "Antanar",
  rasse: "Argarath",
  geschlecht: "männlich",
  namen: [
    "Vaelor",
    "Serion",
    "Ithorak",
    "Ae’Lorin",
    "Zaevir",
    "Thalior",
    "Khaelin",
    "Oryan",
    "Elionek",
    "Naekor",
    "Ularith",
    "Reivos",
    "Varnior",
    "Lyorith",
    "Mirakar",
    "Irethar",
    "Daevin",
    "Kaelion",
    "Yareth",
    "Orimar",
    "Zorion",
    "Aevaris",
    "Thorien",
    "Elkaen",
    "Quorion",
    "Tiraek",
    "Halorin",
    "Eronar",
    "Sylaek",
    "Daethor",
    "Norevak",
    "Iskaron",
    "Orvein",
    "Velarik",
    "Kelonir",
    "Zarion",
    "Phalarin",
    "Therakos",
    "Ilyonak",
    "Aerior"
  ]
},
{
  welt: "Antanar",
  rasse: "Argarath",
  geschlecht: "weiblich",
  namen: [
    "Elyara",
    "Ni’reth",
    "Valenya",
    "Aerelis",
    "Ionnae",
    "Saelira",
    "Aenora",
    "Thiraya",
    "Quirael",
    "Isolwen",
    "Loriven",
    "Yelaeris",
    "Alurea",
    "Norivya",
    "Keirali",
    "Eolwyn",
    "Serenya",
    "Lyarael",
    "Olythea",
    "Veiraen",
    "Shiaris",
    "Faelyra",
    "Zevalin",
    "Inarya",
    "Elaria",
    "Naerelle",
    "Thalyae",
    "Myriena",
    "Rhaelis",
    "Ilaryth",
    "Voenya",
    "Sarivyn",
    "Aniryel",
    "Lureysa",
    "Kaevira",
    "Yorwen",
    "Vaeleia",
    "Eviara",
    "Xalirae",
    "Orlinis"
  ]
}{
  welt: "Antanar",
  rasse: "Waragh",
  geschlecht: "männlich",
  namen: [
    // JARG
    "Krulgar", "Thrakul", "Brontash", "Gharrok", "Varnuk",
    "Drothar", "Grakmor", "Kargash", "Zormak", "Ulthok",
    "Trarnok", "Molgath", "Bruvak", "Thakron", "Durmakh",
    "Ragthor", "Karnag", "Vrogak", "Drullok", "Khurvak",
    "Jolthar", "Krashun", "Brukhor", "Garthul", "Tromgak",
    "Zulmok", "Vorgran", "Thokarn", "Ulgaron", "Karghun",
    "Dronrak", "Varnorak", "Khramok", "Gorvul", "Thrugor",
    
    // BRANDHALL
    "Korveth", "Durnak", "Vrakon", "Torgath", "Haldrak",
    "Mogrel", "Zaruk", "Kurnash", "Bralkur", "Grolthak",
    "Tarmek", "Vekran", "Jorluk", "Dhurmak", "Rorvak",
    "Khalkor", "Throgar", "Gurnath", "Zhorik", "Tralok",
    "Marzun", "Brenkhor", "Gralmek", "Harkun", "Vorkhal",
    "Brothan", "Talgur", "Kharnok", "Drakhal", "Jolgar",
    "Morkhur", "Valthak", "Grovenok", "Darnokh", "Zhulvar",

    // TELPON
    "Thernak", "Jarkhal", "Volgrun", "Traskar", "Kelthor",
    "Durnesh", "Vashrak", "Grolfen", "Khurthak", "Branvek",
    "Sharnok", "Kolvan", "Moltrak", "Krorvek", "Jalgrum",
    "Varthul", "Ralgath", "Zeknar", "Dorvak", "Krelmor",
    "Tharvon", "Murnak", "Brakush", "Ulgroth", "Kharven",
    "Torvun", "Zhurvek", "Grenthur", "Dargash", "Kharnul",
    "Orthak", "Bronvak", "Mulgor", "Kravon", "Ferthak"
  ]
},
{
  welt: "Antanar",
  rasse: "Waragh",
  geschlecht: "weiblich",
  namen: [
    // JARG
    "Thrasha", "Grulka", "Varzha", "Drokha", "Ulmara",
    "Zagrin", "Khurla", "Brasha", "Morghen", "Velkara",
    "Trunja", "Shorvak", "Dor’kael", "Bragha", "Zhurnakha",
    "Tarnusha", "Khalmira", "Zorga", "Frunla", "Makrasha",
    "Drulvina", "Nurgana", "Varkael", "Khazhra", "Tholka",
    "Marnira", "Zhulmira", "Ograsha", "Brezhna", "Ulzara",
    "Kragma", "Drovena", "Throgna", "Yarkael", "Galnasha",
    
    // BRANDHALL
    "Karitha", "Veshra", "Molkara", "Thrima", "Zulvara",
    "Kormetha", "Ashgora", "Brankael", "Yalmira", "Dorzhaka",
    "Sharnika", "Thargasha", "Felrukha", "Ulgana", "Vorkaela",
    "Zemira", "Krelsha", "Naulgra", "Mazhrika", "Dralkia",
    "Garnesha", "Zalvina", "Khurael", "Brulmira", "Thovaka",
    "Yahraka", "Skalnara", "Farnika", "Tarkhira", "Lor’vasha",
    "Uzmira", "Cholvenka", "Mourlasha", "Grenthae", "Ulthraza",

    // TELPON
    "Kelzara", "Thravika", "Darmela", "Shouren", "Karvitha",
    "Velgasha", "Brenika", "Ulthria", "Marzenka", "Zourmira",
    "Kharnesha", "Zalvetta", "Orshaka", "Torvina", "Thulkara",
    "Yazhrika", "Durshira", "Kaelmora", "Brorka", "Jharnika",
    "Kholasha", "Thornael", "Skelvina", "Tralmira", "Drezhara",
    "Zagvika", "Vorthaea", "Yarnasha", "Grumira", "Tharvala",
    "Khazmira", "Dolvira", "Brumetha", "Orvikael", "Nalgrasha"
  ]
}{
  welt: "Antanar",
  rasse: "Kol'Morath",
  geschlecht: "männlich",
  namen: [
    "Azhorak", "Vel’uthen", "Draazir", "Ekravul", "Zal’morith",
    "Khirazun", "Olnashar", "Verazhul", "Mal’korrin", "Urothek",
    "Thraemir", "Xelvaorn", "Zornakhel", "Irshadar", "Kaomirak",
    "Nyrrhoul", "Braethorul", "Velkaruun", "Shaarven", "Kravernesh",
    "Ozzarith", "Thul’Varekh", "Zar’kethar", "Ezhanor", "Morr’vhael",
    "Vexirak", "Dul’marokh", "Nathioren", "Kharzeil", "Zhevaran",
    "Omrethil", "Yrrhakor", "Ulkarion", "Thraneluth", "Baazekhor"
  ]
},
{
  welt: "Antanar",
  rasse: "Kol'Morath",
  geschlecht: "weiblich",
  namen: [
    "Velziah", "Shurazeth", "Kaelyrra", "Zarithya", "Ulvaeja",
    "Morraksha", "Irivhiel", "Ozzineya", "Thashira", "Xyrraleth",
    "Ezmuora", "Nyshael", "Zulvireth", "Var’thaea", "Ounashia",
    "Kiraezhel", "Lhazinae", "Dhaemira", "Yrrhaelis", "Arzeithra",
    "Eshounia", "Zharikael", "Baelyzha", "Ul’nirasha", "Thireya",
    "Kravashi", "Shoumaeth", "Elzoura", "Nazhirae", "Morvelyn",
    "Tzeirael", "Zalveya", "Drexiana", "Lornysha", "Vae'zirra"
  ]
}{
  welt: "Antanar",
  rasse: "Komo Koro",
  geschlecht: "männlich",
  namen: [
    "Kashomo", "Zarouk", "Talviro", "Bagawo", "Kirkakò",
    "Verton", "Nokiri", "Samajon", "Torvani", "Kelmoha",
    "Dakarun", "Junakao", "Vontaro", "Ishaku", "Lomareb",
    "Tarakao", "Bejanok", "Anokaro", "Koshiro", "Maivano",
    "Rakuno", "Tanjori", "Vashono", "Malkata", "Neromai",
    "Fonakeb", "Guvanaro", "Nakaton", "Shoribo", "Juremak",
    "Erovani", "Kalounai", "Mashirok", "Avenako", "Tonaril"
  ]
},
{
  welt: "Antanar",
  rasse: "Komo Koro",
  geschlecht: "weiblich",
  namen: [
    "Aguana", "Nakayato", "Sahiuna", "Kashira", "Lomaya",
    "Venako", "Tiaroma", "Oravina", "Kumanoe", "Jurelia",
    "Talinua", "Enokira", "Vashuma", "Marakoa", "Kirasha",
    "Elaromi", "Naiwenya", "Oshitae", "Zekouna", "Kalimao",
    "Junavari", "Shevonae", "Maekira", "Avanika", "Ronashae",
    "Faliona", "Dasharae", "Mounika", "Karinea", "Soralya",
    "Peliyona", "Onakea", "Kevalin", "Yaruela", "Nashomai"
  ]
}{
  welt: "Antanar",
  rasse: "Korvaku",
  geschlecht: "männlich",
  namen: [
    "Karkikú", "Krkur", "Gar-Gar", "Durnak", "Magashi",
    "Kolvik", "Lakako", "Bronnur", "Grakik", "Varnok",
    "Sho-Krak", "Zulfur", "Muktao", "Kragael", "Ololú",
    "Kharnuk", "Velgrum", "Soesr", "Bakunor", "Draksha",
    "Fonak", "Kek-Kor", "Jukorai", "Rorrek", "Khramun",
    "Burkiro", "Trok’Kak", "Darakik", "Krelmor", "Zhan-Khu",
    "Golvak", "Naroro", "Vek’Ten", "Rugrul", "Palpiku"
  ]
},
{
  welt: "Antanar",
  rasse: "Korvaku",
  geschlecht: "weiblich",
  namen: [
    "Lakaki", "Magusha", "Kiki’Ro", "Soesra", "Toliva",
    "Nar-Nar", "Vekiri", "Zara’Pok", "Ushi’ka", "Karu’Mu",
    "Pikael", "Gogota", "Mokmari", "Velsha", "Sha-Kiki",
    "Onaelu", "Krukula", "Bar’Shee", "Jolika", "Elzaka",
    "Rani’Khu", "Tik-Ka", "Farnuqa", "Zurika", "Molali",
    "Pe’Ruka", "Gava’Noa", "Donakae", "Khi’Luna", "Tula-Mae",
    "Yel’ka", "Nekri’a", "Shimoa", "Luk’voa", "Kari-Kò"
  ]
}{
  welt: "Antanar",
  rasse: "Aruhka",
  geschlecht: "männlich",
  namen: [
    "Nahkan", "Kalumn", "Alhanen", "Shalonin", "Karuan",
    "Gorhin", "Lakokan", "Taokle", "Lakoi", "Thurakem",
    "Duvarek", "Monahal", "Jarhon", "Iverak", "Tarnol",
    "Khalorin", "Ravhen", "Dorakai", "Elunak", "Vaeron",
    "Uroklem", "Zahnen", "Koreth", "Salinar", "Thokarn",
    "Eshalom", "Barikan", "Oulak", "Mirenak", "Kurelen",
    "Asharun", "Volakem", "Jarnol", "Nelmarok", "Lorhanek",
    "Durionak", "Farnak", "Zolhen", "Omarek", "Tarukel"
  ]
},
{
  welt: "Antanar",
  rasse: "Aruhka",
  geschlecht: "weiblich",
  namen: [
    "Shayana", "Lakira", "Moraya", "Thaliena", "Zanika",
    "Oramei", "Narela", "Valhira", "Ishani", "Kerina",
    "Yunara", "Alvara", "Durelia", "Ravitha", "Kelamea",
    "Olunari", "Sahlira", "Teshona", "Varelia", "Elmira",
    "Kovasha", "Thamira", "Naevara", "Ruhkana", "Yelana",
    "Marheka", "Khamina", "Shaenora", "Dahlira", "Kaelunai",
    "Lorvaya", "Velorna", "Ashina", "Niraeli", "Zavhira",
    "Tulmea", "Ushara", "Felana", "Mireka", "Jelvani"
  ]
}{
  welt: "Antanar",
  rasse: "Dunkelemenschen",
  geschlecht: "männlich",
  namen: [
    "Tharnok", "Zulvak", "Khorien", "Draalom", "Ashrok",
    "Vaerun", "Umekal", "Irhoun", "Nokhael", "Elshrak",
    "Khravon", "Ulgareth", "Velmorak", "Zarvash", "Moruzar",
    "Sholtar", "Dornek", "Fhaelon", "Zhurkan", "Ekranil",
    "Narveth", "Talgorin", "Xulmarok", "Varnirh", "Ouzhek"
  ]
},
{
  welt: "Antanar",
  rasse: "Dunkelemenschen",
  geschlecht: "weiblich",
  namen: [
    "Shavrae", "Irthala", "Valeshka", "Ounara", "Drelmira",
    "Elzhani", "Kaelira", "Ashouma", "Tharvelis", "Zhonirae",
    "Korunae", "Yevrashia", "Nalkaes", "Zulmerei", "Lorthira",
    "Veskael", "Or’Masha", "Ivalour", "Sharvetha", "Ulnaree",
    "Dhaesira", "Xomaela", "Vaelasha", "Fharaeli", "Khaelirae"
  ]
}{
  welt: "Antanar",
  rasse: "Menschen",
  geschlecht: "männlich",
  namen: [
    "Talviro", "Darvon", "Eldarik", "Jornas", "Malvenor",
    "Kaldrik", "Lorian", "Thomaril", "Arvak", "Veylen",
    "Jomarion", "Fenlor", "Brymir", "Alroth", "Emonar",
    "Tharik", "Gavron", "Kelvon", "Ilmorin", "Barenok",
    "Tyrial", "Faeron", "Marnic", "Odrik", "Zaelrin"
  ]
},
{
  welt: "Antanar",
  rasse: "Menschen",
  geschlecht: "weiblich",
  namen: [
    "Milara", "Elira", "Rinae", "Thalira", "Seriva",
    "Avrielle", "Kaelenia", "Velra", "Norasha", "Aemira",
    "Vionna", "Lorishae", "Tashira", "Miraina", "Olvara",
    "Camirae", "Jeyna", "Isara", "Fenya", "Aurenya",
    "Kalmira", "Ylenor", "Othira", "Shireen", "Zaela"
  ]
}